package repl

import "github.com/chzyer/readline"

// datastoreItems are the completion children for --source and --target flags
// that accept a datastore name.
var datastoreItems = []readline.PrefixCompleterInterface{
	readline.PcItem("running"),
	readline.PcItem("candidate"),
	readline.PcItem("startup"),
}

// Completer is the full flag-aware tab-completion tree for the REPL.
// It is exported so tests can inspect it.
var Completer = readline.NewPrefixCompleter(
	readline.PcItem("connect",
		readline.PcItem("--host"),
		readline.PcItem("--port"),
		readline.PcItem("--user"),
		readline.PcItem("--password"),
		readline.PcItem("--key"),
		readline.PcItem("--insecure"),
	),
	readline.PcItem("disconnect"),
	readline.PcItem("get",
		readline.PcItem("--filter"),
		readline.PcItem("--subtree"),
		readline.PcItem("--raw"),
	),
	readline.PcItem("get-config",
		readline.PcItem("--source", datastoreItems...),
		readline.PcItem("--filter"),
		readline.PcItem("--subtree"),
		readline.PcItem("--raw"),
	),
	readline.PcItem("edit-config",
		readline.PcItem("--target", datastoreItems...),
		readline.PcItem("--operation",
			readline.PcItem("merge"),
			readline.PcItem("replace"),
			readline.PcItem("none"),
		),
		readline.PcItem("--config"),
	),
	readline.PcItem("copy-config",
		readline.PcItem("--source", datastoreItems...),
		readline.PcItem("--target", datastoreItems...),
	),
	readline.PcItem("delete-config",
		readline.PcItem("--target", datastoreItems...),
	),
	readline.PcItem("lock",
		readline.PcItem("--target", datastoreItems...),
	),
	readline.PcItem("unlock",
		readline.PcItem("--target", datastoreItems...),
	),
	readline.PcItem("commit",
		readline.PcItem("--confirmed"),
		readline.PcItem("--timeout"),
	),
	readline.PcItem("discard"),
	readline.PcItem("validate",
		readline.PcItem("--source", datastoreItems...),
	),
	readline.PcItem("kill-session",
		readline.PcItem("--id"),
	),
	readline.PcItem("capabilities"),
	readline.PcItem("help"),
	readline.PcItem("version"),
	readline.PcItem("exit"),
	readline.PcItem("quit"),
)
