// RFC 6470 notification body types (ietf-netconf-notifications YANG module).
//
// # Decoding Notification.Body
//
// [Notification.Body] uses xml:",innerxml" which, combined with the EventTime
// named child, means Body will contain both the <eventTime> bytes and the
// notification-specific element as sibling nodes. Calling xml.Unmarshal
// directly on Body will therefore fail because xml.Unmarshal expects a single
// root element.
//
// Callers must wrap Body in a synthetic root element before decoding:
//
//	var cc ConfigChange
//	wrapped := append([]byte("<w>"), append(n.Body, []byte("</w>")...)...)
//	var wrapper struct {
//	    CC ConfigChange `xml:"netconf-config-change"`
//	}
//	if err := xml.Unmarshal(wrapped, &wrapper); err != nil { … }
//	cc = wrapper.CC

package netconf

import "encoding/xml"

// NetconfNotificationsNS is the XML namespace for RFC 6470 NETCONF notification
// body types (ietf-netconf-notifications YANG module, RFC 6470 §5).
//
// This namespace is distinct from NotificationNS (RFC 5277 envelope namespace)
// and from NetconfNS (RFC 6241 base namespace).
const NetconfNotificationsNS = "urn:ietf:params:xml:ns:yang:ietf-netconf-notifications"

// ChangedBy encodes the YANG choice "server-or-user" used by several RFC 6470
// notification types to identify the initiator of a change.
//
// Mutual exclusion is enforced by callers: set Server to &struct{}{} for a
// server-initiated change, or populate Username/SessionID/SourceHost for a
// user-initiated change. The library does not validate the choice at runtime.
//
//   - Server:     present as <server/> when the change was made by the server itself.
//   - Username:   NETCONF username of the user session (user-initiated change).
//   - SessionID:  NETCONF session-id of the user session; omitted when zero.
//   - SourceHost: IP address or hostname of the session source; omitted when empty.
type ChangedBy struct {
	Server     *struct{} `xml:"server,omitempty"`
	Username   string    `xml:"username,omitempty"`
	SessionID  uint32    `xml:"session-id,omitempty"`
	SourceHost string    `xml:"source-host,omitempty"`
}

// EditRecord describes a single edit operation within a ConfigChange
// notification (RFC 6470 §4.1).
//
//   - Target:    canonical name of the datastore edited (e.g. "running").
//   - Operation: NETCONF edit operation applied (e.g. "merge", "replace", "delete").
type EditRecord struct {
	Target    string `xml:"target"`
	Operation string `xml:"operation"`
}

// ConfigChange is the RFC 6470 netconf-config-change notification body.
// It is generated by the server when the NETCONF configuration datastore is
// modified. Callers unmarshal this from [Notification.Body] using the
// synthetic-wrapper pattern described in the package godoc.
//
//   - ChangedBy:  who initiated the change (server or user session).
//   - Datastore:  which datastore was changed; omitted when empty (implies "running").
//   - Edit:       list of individual edit records; omitted when empty.
type ConfigChange struct {
	XMLName   xml.Name     `xml:"urn:ietf:params:xml:ns:yang:ietf-netconf-notifications netconf-config-change"`
	ChangedBy ChangedBy    `xml:"changed-by"`
	Datastore string       `xml:"datastore,omitempty"`
	Edit      []EditRecord `xml:"edit,omitempty"`
}

// CapabilityChange is the RFC 6470 netconf-capability-change notification
// body. It is generated when a server's capabilities change at runtime.
// Callers unmarshal this from [Notification.Body] using the synthetic-wrapper
// pattern described in the package godoc.
//
//   - ChangedBy:          who initiated the capability change.
//   - AddedCapability:    list of newly added capability URIs; omitted when empty.
//   - DeletedCapability:  list of removed capability URIs; omitted when empty.
//   - ModifiedCapability: list of modified capability URIs; omitted when empty.
type CapabilityChange struct {
	XMLName            xml.Name  `xml:"urn:ietf:params:xml:ns:yang:ietf-netconf-notifications netconf-capability-change"`
	ChangedBy          ChangedBy `xml:"changed-by"`
	AddedCapability    []string  `xml:"added-capability,omitempty"`
	DeletedCapability  []string  `xml:"deleted-capability,omitempty"`
	ModifiedCapability []string  `xml:"modified-capability,omitempty"`
}

// SessionStart is the RFC 6470 netconf-session-start notification body.
// It is generated when a new NETCONF session is established.
// Callers unmarshal this from [Notification.Body] using the synthetic-wrapper
// pattern described in the package godoc.
//
//   - Username:   NETCONF username of the new session (required).
//   - SessionID:  NETCONF session-id assigned to the session (required).
//   - SourceHost: IP address or hostname of the client; omitted when absent.
type SessionStart struct {
	XMLName    xml.Name `xml:"urn:ietf:params:xml:ns:yang:ietf-netconf-notifications netconf-session-start"`
	Username   string   `xml:"username"`
	SessionID  uint32   `xml:"session-id"`
	SourceHost string   `xml:"source-host,omitempty"`
}

// SessionEnd is the RFC 6470 netconf-session-end notification body.
// It is generated when an existing NETCONF session is terminated.
// Callers unmarshal this from [Notification.Body] using the synthetic-wrapper
// pattern described in the package godoc.
//
//   - Username:          NETCONF username of the terminated session (required).
//   - SessionID:         NETCONF session-id of the terminated session (required).
//   - SourceHost:        IP address or hostname of the client; omitted when absent.
//   - KilledBy:          session-id of the session that issued <kill-session>; zero
//     (omitted) when TerminationReason is not "killed".
//   - TerminationReason: reason for termination (required). One of: "closed",
//     "killed", "dropped", "timeout", "bad-hello", "other".
type SessionEnd struct {
	XMLName           xml.Name `xml:"urn:ietf:params:xml:ns:yang:ietf-netconf-notifications netconf-session-end"`
	Username          string   `xml:"username"`
	SessionID         uint32   `xml:"session-id"`
	SourceHost        string   `xml:"source-host,omitempty"`
	KilledBy          uint32   `xml:"killed-by,omitempty"`
	TerminationReason string   `xml:"termination-reason"`
}

// ConfirmedCommit is the RFC 6470 netconf-confirmed-commit notification
// body. It is generated at each stage of a confirmed-commit sequence.
// Callers unmarshal this from [Notification.Body] using the synthetic-wrapper
// pattern described in the package godoc.
//
//   - Username:     NETCONF username; omitted when ConfirmEvent is "timeout" (no session).
//   - SessionID:    session-id; omitted when ConfirmEvent is "timeout" (no session).
//   - SourceHost:   client IP or hostname; omitted when absent.
//   - ConfirmEvent: event type (required). One of: "start", "cancel", "timeout",
//     "extend", "complete".
//   - Timeout:      remaining timeout in seconds; omitted when not applicable.
type ConfirmedCommit struct {
	XMLName      xml.Name `xml:"urn:ietf:params:xml:ns:yang:ietf-netconf-notifications netconf-confirmed-commit"`
	Username     string   `xml:"username,omitempty"`
	SessionID    uint32   `xml:"session-id,omitempty"`
	SourceHost   string   `xml:"source-host,omitempty"`
	ConfirmEvent string   `xml:"confirm-event"`
	Timeout      uint32   `xml:"timeout,omitempty"`
}
